# Generated by Django 2.2.6 on 2019-10-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('rate_id', models.CharField(help_text='id курса валюты', max_length=10, verbose_name='rate ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование валюты')),
                ('value', models.CharField(max_length=10, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
